### ISSUE TITLE
It does not import sessions nor domains

### ISSUE THREAD

**Issue by thau0x01** [helviojunior/knowsmore#6]
### Configuration  
impacket version:  0.11.0
Python version:  Python 3.11.3
Target OS:  OS X / Linux (I tested on both OSes)

### Debug Output With Command String  
i.e.  
```
knowsmore --bloodhound --import-data 20230815164740_bloodhound.zip --enable-group-chain --company customer
```
   
```
KnowsMore v0.1.30 by Helvio Junior
Active Directory, BloodHound, NTDS hashes and Password Cracks correlation tool
https://github.com/helviojunior/knowsmore

 [+] Startup parameters
     command line: knowsmore --bloodhound --import-data 20230815164740_bloodhound.zip --enable-group-chain --company customer
     module: bloodhound
     company name: customer
     operational mode: ImportMode.Import
     database file: /Users/user/engagements/customer/knowsmore.db

 [+] start time 2023-08-17 20:36:34
 [?] BloodHound ZIP File identified, extracting...
 [?] checking file consistency...
 [?] invalid file: /Users/user/engagements/customer/EWLHritwiuLwkpdmJYTw/20230815164740_domains.json
 [?] 5 valid files in ZIP
 [?] importing domains...
 [?] importing GPO...
 [?] importing OU...
 [?] importing groups...
 [?] calculating group chain...
 [?] importing computers...
 [?] loading groups from db...
 [?] importing users...
 [+] Imported objects

 [!] Error: list index out of range

 [!] Full stack trace below

 [!]    Traceback (most recent call last):
 [!]    File "/usr/local/lib/python3.11/site-packages/knowsmore/knowsmore.py", line 62, in run
 [!]        Configuration.module.run()
 [!]    File "/usr/local/lib/python3.11/site-packages/knowsmore/cmd/bloodhound.py", line 816, in run
 [!]        Color.pl('%s' % Tools.get_tabulated(imported))
 [!]                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 [!]    File "/usr/local/lib/python3.11/site-packages/knowsmore/util/tools.py", line 88, in get_tabulated
 [!]        headers = [(h if h[0:2] != '__' else ' ') for h in data[0].keys()]
 [!]                                                           ~~~~^^^
 [!]    IndexError: list index out of range
 [+] End time 2023-08-17 20:38:16
```

### Additional context  
Space for additional context, investigative results, suspected issue.

When ingesting data using the latest BloodHound GUI App, it recognizes the domains in the forest and user sessions on computers.

**Comment by thau0x01** [comment]
I'm going to take a look a this in the weekend and submit a PR. Just sent the issue to get it documented here.

**Comment by helviojunior** [comment]
Hi @thau0x01 thanks for the issue report. This Bug is fixed at main branch, I Just not released the new version.

I'm releasing the version 0.1.32 with this bugfix

**Comment by thau0x01** [comment]
Nice man! Thx! 👍🏻
